name: build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.OSS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.OSS_DOCKERHUB_PASSWORD }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./mvnw -C -B clean install -DskipTests

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            from_image=gcr.io/distroless/java17-debian11
          tags: |
            ybrig/concord-agent-operator:0.3.0-SNAPSHOT
